### PR TITLE
fix(profiling): fix SystemError when collecting memory profiler events

### LINKED ISSUE #11831: [BUG]: SystemError: <class 'iter_events'> returned NULL without setting an exception
### Tracer Version(s)

2.18.1

### Python Version(s)

Python 3.11.9

### Pip Version(s)

24.0

### Bug Report

We have started seeing the following exceptions after upgrading to version 2.18.1
```
SystemError: <class 'iter_events'> returned NULL without setting an exception
  File "ddtrace/profiling/collector/__init__.py", line 43, in periodic
    for events in self.collect():
  File "ddtrace/profiling/collector/memalloc.py", line 175, in collect
    events_iter, count, alloc_count = _memalloc.iter_events()
```

### Reproduction Code

_No response_

### Error Logs

_No response_

### Libraries in Use

aioboto3==13.2.0
aiobotocore==2.15.2
aiocache==0.12.3
aiodogstatsd==0.16.0.post0
aiofiles==24.1.0
aiohappyeyeballs==2.4.4
aiohttp==3.11.10
aioitertools==0.12.0
aiomcache==0.8.2
aioredis==2.0.1
aiosignal==1.3.2
annotated-types==0.7.0
argcomplete==3.3.0
async-timeout==5.0.1
attrs==24.3.0
azure-core==1.32.0
azure-identity==1.19.0
backoff==2.2.1
boto3==1.35.36
botocore==1.35.36
build==1.2.2.post1
certifi==2024.12.14
cffi==1.17.1
charset-normalizer==3.4.0
click==8.1.7
cryptography==44.0.0
defusedxml==0.7.1
dnspython==2.7.0
docopt==0.4.0
email_validator==2.2.0
fastavro==1.9.7
frozenlist==1.5.0
gitdb==4.0.11
GitPython==3.1.43
idna==3.10
Jinja2==3.1.4
jira==3.8.0
jmespath==1.0.1
mandrill==1.0.60
MarkupSafe==2.1.5
msal==1.31.1
msal-extensions==1.2.0
msgpack==1.1.0
multidict==6.1.0
oauthlib==3.2.2
packaging==24.0
pbr==6.0.0
pillow==10.3.0
pip-tools==7.4.1
pipx==1.5.0
platformdirs==4.2.2
portalocker==2.10.1
propcache==0.2.1
pycparser==2.22
pydantic==2.10.3
pydantic-settings==2.7.0
pydantic_core==2.27.1
PyJWT==2.10.1
pyOpenSSL==24.3.0
pyproject_hooks==1.2.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
redis==5.2.1
requests==2.32.3
requests-oauthlib==2.0.0
requests-toolbelt==1.0.0
s3transfer==0.10.4
six==1.17.0
smmap==5.0.1
typing_extensions==4.12.2
ujson==5.10.0
urllib3==2.2.3
userpath==1.9.2
wrapt==1.17.0
yarl==1.18.3

### Operating System

_No response_

### PR DESCRIPTION
**Pull request by nsrip-dd**
We added locking to the memory profiler to address crashes. These locks
are mostly "try" locks, meaning we bail out if we can't acquire them
right away. This was done defensively to mitigate the possibility of
deadlock until we fully understood why the locks are needed and could
guarantee their correctness. But as a result of using try locks, the
`iter_events` function in particular can fail if the memory profiler lock
is contended when it tries to collect profiling events. The function
then returns NULL, leading to SystemError exceptions because we don't
set an error.

Even if we set an error, returning NULL isn't the right thing to do.
It'll basically mean we wait until the next profile iteration, still
accumulating events in the same buffer, and try again to upload the
events. So we're going to get multiple iteration's worth of events. The
right thing to do is take the lock unconditionally in `iter_events`. We
can allocate the new tracker outside the memory allocation profiler lock
so that we don't need to worry about reentrancy/deadlock issues if
we start profiling that allocation. Then, the only thing we do under the
lock is swap out the global tracker, so it's safe to take the lock
unconditionally.

Fixes #11831

TODO - regression test?

## Checklist
- [x] PR author has checked that all the criteria below are met
- The PR description includes an overview of the change
- The PR description articulates the motivation for the change
- The change includes tests OR the PR description describes a testing strategy
- The PR description notes risks associated with the change, if any
- Newly-added code is easy to change
- The change follows the [library release note guidelines](https://ddtrace.readthedocs.io/en/stable/releasenotes.html)
- The change includes or references documentation updates if necessary
- Backport labels are set (if [applicable](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting))

## Reviewer Checklist
- [x] Reviewer has checked that all the criteria below are met 
- Title is accurate
- All changes are related to the pull request's stated goal
- Avoids breaking [API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces) changes
- Testing strategy adequately addresses listed risks
- Newly-added code is easy to change
- Release note makes sense to a user of the library
- If necessary, author has acknowledged and discussed the performance implications of this PR as reported in the benchmarks PR comment
- Backport labels are set in a manner that is consistent with the [release branch maintenance policy](https://ddtrace.readthedocs.io/en/latest/contributing.html#backporting)

### CODE REVIEW

File: ddtrace/profiling/collector/_memalloc.c [hunk 1]
```diff
@@ -394,20 +394,18 @@ iterevents_new(PyTypeObject* type, PyObject* Py_UNUSED(args), PyObject* Py_UNUSE
     }
 
     IterEventsState* iestate = (IterEventsState*)type->tp_alloc(type, 0);
-    if (!iestate)
+    if (!iestate) {
+        PyErr_SetString(PyExc_RuntimeError, "failed to allocate IterEventsState");
```
Comment (P403n1x87) [inline ddtrace/profiling/collector/_memalloc.c:398]: Is the exception handled somewhere?

Comment (nsrip-dd) [reply ddtrace/profiling/collector/_memalloc.c:398]: Yeah, it's handled here: https://github.com/DataDog/dd-trace-py/blob/b90fa382764908d0bf11c84cbd097ad9f1a49a27/ddtrace/profiling/collector/memalloc.py#L170-L179

Comment (taegyunkim) [reply ddtrace/profiling/collector/_memalloc.c:398]: https://github.com/DataDog/dd-trace-py/blob/71e3997e0eaf549e4c96f2af8b9ceebe01faf3b7/ddtrace/profiling/collector/memalloc.py#L174-L179

Yes, we do handle RuntimeError here.

**Review by sanchda — APPROVED** [review]

File: ddtrace/profiling/collector/_memalloc.c [hunk 2]
```diff
@@ -394,20 +394,18 @@ iterevents_new(PyTypeObject* type, PyObject* Py_UNUSED(args), PyObject* Py_UNUSE
...
     /* reset the current traceback list */
-    if (memlock_trylock(&g_memalloc_lock)) {
-        iestate->alloc_tracker = global_alloc_tracker;
-        global_alloc_tracker = alloc_tracker_new();
-        memlock_unlock(&g_memalloc_lock);
-    } else {
-        Py_TYPE(iestate)->tp_free(iestate);
-        return NULL;
-    }
+    memlock_lock(&g_memalloc_lock);
```
Comment (taegyunkim) [inline ddtrace/profiling/collector/_memalloc.c:405]: Since we're changing from `try_lock` to `lock`, would this be safe from indefinitely blocking?

**Review by taegyunkim — APPROVED** [review]

File: ddtrace/profiling/collector/_memalloc.c (hunk 2 above)
Comment (nsrip-dd) [reply ddtrace/profiling/collector/_memalloc.c:413]: Good idea. I actually ended up pulling the allocation of the new tracker outside the lock in https://github.com/DataDog/dd-trace-py/pull/12075/commits/6c682abdf1e819c5dcb6c19d00d309b70c3bcefe, and added a comment for why. Please take another look 🙏
